Zips\Bundle\MainBundle\Entity\Logs:
    type: entity
    table: Logs
    indexes:
        idUsuario:
            columns:
                - idUsuario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datahora:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: dataHora
        mensagem:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idusuario:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
