parameters:
#    zips_main.example.class: Zips\Bundle\MainBundle\Example

services:
#    zips_main.example:
#        class: %zips_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
